[tool.poetry]
name = "pyrcrack"
version = "0.1.2"
description = ""
authors = ["David Francos <opensource@davidfrancos.net>"]

[tool.poetry.dependencies]
python = "^3.7"
stringcase = "^1.2"
docopt = "^0.6.2"
async-timeout = "^3.0"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0"
pycodestyle = "^2.5"
pytest-cov = "^2.6"
asynctest = "^0.12.3"
pydocstyle = "^3.0"
sphinx = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
